services:
  jsoncrack:
    image: jsoncrack
    container_name: jsoncrack
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '100.84.3.80:8888:8888'
    environment:
      - NODE_ENV=production